Create the layout for authenticated pages
Jezda1337/taskify pull request #9
Opened 2022-11-04 10:13 UTC by Ninjaneer87

2022-11-06 18:07 UTC, Jezda1337 requested changes
There is couple of comments and consoles logs that we don't need, pls remove them and we can merge 😀

2022-11-06 18:07 UTC, Jezda1337 commented on styles/theme/lightThemeOptions.ts
> +    // text: {
If we don't need this comments we can remove them

2022-11-06 18:07 UTC, Jezda1337 commented on components/shared/layout/appbar/menus/SearchBarMenu.tsx
> +    console.log("Search submitted");
I guess we don't need this one

2022-11-06 18:07 UTC, Jezda1337 commented on components/shared/layout/drawer/DrawerMobile.tsx
> +      console.log("scrolling");
this one as well

2022-11-07 06:54 UTC, Ninjaneer87 commented
Nice catch! All done ! B)

2022-11-07 06:56 UTC, merged